### ISSUE TITLE
Removing stale models

### ISSUE THREAD

**Issue by alvations** [nltk/nltk_data#104]
From nltk/nltk#428 , nltk/nltk#69 and nltk/nltk#1783 , these models in `nltk_data` can no longer be used so they should be removed:

 - nltk_data/packages/taggers/hmm_treebank_pos_tagger.zip
 - nltk_data/packages/chunkers/treebank.chunker.pickle.gz
 - nltk_data/packages/chunkers/muc6.chunk.tagger.pickle.gz

**Comment by stevenbird** [comment]
Is there any legacy value in keeping them around, e.g. for old deployments?

**Comment by alvations** [comment]
Don't think so I can't unpickle them with python 2.7 and we don't support Python < 2.7 anymore.

**Comment by stevenbird** [comment]
Ah, ok! Thanks @alvations

**Comment by alvations** [comment]
Thanks for removing them!
