### ISSUE TITLE
brown.zip (possible others) corrupt

### ISSUE THREAD

**Issue by chadgh** [nltk/nltk_data#11]
When I attempt to download the brown.zip corpus and extract with the nltk tools I get the message "Error with downloaded zip file".

When I attempt to download it manually it seems to download just fine, but then when I go to extract manually:

``` bash
$ unzip brown.zip
Archive:  brown.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of brown.zip or
        brown.zip.zip, and cannot find brown.zip.ZIP, period.
```

**Comment by alvations** [comment]
Sorry for missing this issue out. There shouldn't be any problem with the `brown.zip` now in the latest version of `nltk` and `nltk_data`. @chadgh is this still an issue for you?

**Comment by chadgh** [comment]
@alvations no problem. This does work now.
