### ISSUE TITLE
Data as PyPi packages

### ISSUE THREAD

**Issue by triztian** [nltk/nltk_data#12]
It would be nicer or even more usable to have each data package as a python pypi package. That way they could be installed using the pip installer. Instead of using the `text.download()` method and interactive installer

**Comment by andybergon** [comment]
Also with this we can make the data packages versionated and make possible to download always the same data if you want.

**Comment by andybergon** [comment]
@stevenbird
Was this closed as wad/won't fix?

**Comment by bittner** [comment]
Why was this closed?

Downloading package data with a custom, hand-crafted download process might have been an okay-ish solution ten years ago, but Python usage, popularity and supply-chain attacks have changed the picture. What used to be a convenient process automation in the past is now identified as a potential attack vector. Banks and other large organizations, for example, don't allow direct downloads from the Internet anymore. Python packages _must_ be downloaded from PyPI and are scanned for vulnerabilities. What is custom and non-standard is considered hackers' terrain and thus potentially dangerous.

In NLTK the non-standard installation process is also a common source of error and confusion, it's a darn usability issue.

It's cool that this repository has the package data all neatly separate and generates an index from it. This process can be naturally extended to build a Python package for each of them and push them to PyPI, one after the other. A single project template should suffice to do that, I think.
