### ISSUE TITLE
Chinese simplified stopwords

### ISSUE THREAD

**Issue by zetta-224** [nltk/nltk_data#137]
[chinese_simplified_stopwords.txt](https://github.com/nltk/nltk_data/files/3339044/chinese_simplified_stopwords.txt)

**Comment by stevenbird** [comment]
What is the source of these?

**Comment by zetta-224** [comment]
https://github.com/goto456/stopwords/blob/master/%E7%99%BE%E5%BA%A6%E5%81%9C%E7%94%A8%E8%AF%8D%E8%A1%A8.txt

He says this stopwords list is from BAIDU, the largest simplified Chinese searching engine. 
I have checked it and deleted part of words which contain non-Chinese characters.

**Comment by Alqua** [comment]
It would be great to have chinese on ntlk

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk_data/commit/aa54613807a97886516d5f0d13c1374d29bf4257
Sorry for the long delay
