### ISSUE TITLE
Slovene stowords have additional spaces at the end of each word

### ISSUE THREAD

**Issue by PrimozGodec** [nltk/nltk_data#139]
I just found out that Slovene stopwords have additional space at the end of each word. I think they should be removed otherwise it needs to be done in the application.

I was trying to find the file with stopwords in this repo, but I couldn't find it.

**Comment by PrimozGodec** [comment]
I can fix this issue. Can you just let me know what file to edit?

**Comment by stevenbird** [comment]
Thanks for reporting this @PrimozGodec
