### ISSUE TITLE
Upgrade CMUDict to 0.7b

### ISSUE THREAD

**Issue by begeekmyfriend** [nltk/nltk_data#142]
Hey, thanks for your brilliant jobs! I notice the version of the CMUDict package is not the latest one yet. Would you please upgrade CMUDict version to 0.7b?

**Comment by light1726** [comment]
Looks like you have done some modifications to the CMUDict file, making users cannot simply replace the file with its newer version to update the dictionary. It would be easier for updating if you use the original CMUDict file.

**Comment by begeekmyfriend** [comment]
Thank you!
