### ISSUE TITLE
Update Universal Tagset mapping data

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk_data#15]
Source: https://code.google.com/p/universal-pos-tags/
Cf: https://groups.google.com/forum/#!topic/nltk-users/IwKDLMZzZGw

**Comment by nschneid** [comment]
Can somebody update to the latest version at https://github.com/slavpetrov/universal-pos-tags ? The NR-TL and NR-TL-HL mappings to `NOUN` are still missing (though now instead of throwing an error, they are mapped by default to the `X` tag).
