### ISSUE TITLE
downloader error what do I do?

### ISSUE THREAD

**Issue by havesthdone** [nltk/nltk_data#150]
Hi,
I've got an error msg: Errno 11004 getaddrinfo failed when using nlkt.download().
I'd like to know how can I fix this.
Do I need to download everything from nltk_data and put somewhere manually? Would it work?
Thanks.

**Comment by havesthdone** [comment]
And you know I'm learning it so please help.

**Comment by Amanda-Clark** [comment]
Can you share the full context of your code that is failing?
