### ISSUE TITLE
Extended Open Multilingual WordNet

### ISSUE THREAD

**Issue by ExplorerFreda** [nltk/nltk_data#179]
- Source of the corpus: http://compling.hss.ntu.edu.sg/omw/wn-wikt.zip (zip), retrieved from http://compling.hss.ntu.edu.sg/omw/summx.html 
- Suggested NLTK name for the corpus: `extended_omw`
- Corpus reader: I've created a new corpus reader (class name: `ExtendedOpenMultilingualWordNetCorpusReader`; will open a pull request to the NLTK repo soon) based on the existing wordnet reader. 
- Redistribution:  "The complete data collected from Wiktionary is released under a CC by SA 3.0 Licence, and the complete data collected from CLDR is released under the Unicode, Inc. Licence Agreement." --quoted from the original corpus website: http://compling.hss.ntu.edu.sg/omw/summx.html

**Comment by stevenbird** [comment]
Thanks @ExplorerFreda
