### ISSUE TITLE
Update license for universal-pos-tags

### ISSUE THREAD

**Issue by mrahtz** [nltk/nltk_data#189]
On the NLTK Data page, https://www.nltk.org/nltk_data, the data pack "Mappings to the Universal Part-of-Speech Tagset" doesn't have author, license, or source set. I think the correct values are:

Author: Slav Petrov
License: CC-BY-SA-4.0
Source: https://github.com/slavpetrov/universal-pos-tags

Thanks!

**Comment by stevenbird** [comment]
I've added this to the metadata at: https://github.com/nltk/nltk_data/blob/gh-pages/packages/taggers/universal_tagset.xml
(Not sure why it isn't showing up on the webpage)

**Comment by mrahtz** [comment]
Thanks!
