### ISSUE TITLE
Server Index link is not working

### ISSUE THREAD

**Issue by thewebcoder2009** [nltk/nltk_data#192]
The link https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml from where the nltk downloads model is not working for me. Whenever I try to open it manually it shows raw.githubusercontent.com took too long to respond. And when python tries to download it shows "Error loading punkt: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>"

How do I fix this.
Note :- My network is good also.

**Comment by tomaarsen** [comment]
Hello!

You're not the only one who's been experiencing these issues:
* https://github.com/nltk/nltk/issues/3092
* https://github.com/nltk/nltk/issues/3093
* https://github.com/nltk/nltk/issues/3094

However, I just can't seem to reproduce the issues. https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml loads perfectly for me, in all of my browsers, and even on my phone. The website is simply this GitHub page: https://github.com/nltk/nltk_data/blob/gh-pages/index.xml, and then clicking on "raw" to get only the content from `index.xml`. With other words, this isn't some shady or inconsistent host, it's GitHub themselves. Perhaps you can load the page by clicking on the "raw" button on that page?

I've tried a few websites that check whether a site is pingable or not, and most seem to report that the site is accessible. I'm not quite sure what I can do about this.

**Comment by thewebcoder2009** [comment]
By clicking raw button then also it is showing same error

**Comment by tomaarsen** [comment]
This seems to indeed be caused by https://raw.githubusercontent.com sometimes being down. I don't think there's much I can do about that.

**Comment by thewebcoder2009** [comment]
Hmm... OK Thanks for replying

**Comment by tomaarsen** [comment]
@thecoder1234-ssvbhilai There's a bit more info and a workaround here: https://github.com/nltk/nltk/issues/3092#issuecomment-1366526151

**Comment by thewebcoder2009** [comment]
still not working

**Comment by tomaarsen** [comment]
Some users are suggesting that this is a DNS error. Please look here: https://github.com/nltk/nltk/issues/3092#issuecomment-1374990896.

**Comment by AnkitDubey040** [comment]
I was also facing the same problem , but for India I can say the problem is with Jio Internet used , it is somehow causing the problem , when i am using different network for wifi like BSNL or Airtel then it is working fine

**Comment by thewebcoder2009** [comment]
yes I am also using jio fiber

**Comment by Feruz00** [comment]
I very tired this error. Many days try solve this error. I have too error. Network good. Only get error. If I cannot fix this , can I download nltk files without python code?

**Comment by tomaarsen** [comment]
Yes, you can download the NLTK files without Python code: https://github.com/nltk/nltk/issues/3092#issuecomment-1398658093
There are some useful things to try in that thread.
