### ISSUE TITLE
Re-train maxent_treebank_pos_tagger

### ISSUE THREAD

**Issue by kmike** [nltk/nltk_data#3]
It currently doesn't unpickle under Python3.x. I guess this is because of http://bugs.python.org/issue6784 : Treebank corpus reader returned bytestrings under Python 2.x and the pickled classifier was trained on it; Python 3.x tries to decode them to unicode and this fails because the encoding is unknown. I think the way to fix this is to re-train the classifier on Python 2.x but with unicode strings as features; this should be backwards-compatible if I'm not mistaken.

**Comment by alvations** [comment]
Superseded by new `averaged_perceptron_tagger`
