### ISSUE TITLE
Inclusion of MULTEXT-East Corpus

### ISSUE THREAD

**Issue by stieglma** [nltk/nltk_data#30]
Hi,
 @jwacalex @toydarian and I are currently working on a corpus reader and POS-Tagger for the MULTEXT-East corpus for a project in a text-mining course at the University of Passau.
It would be great if our work could be integrated into NLTK. The first step therefore would be to add the corpus to your repository. It is available at https://www.clarin.si/repository/xmlui/handle/11356/1043 the license is CC BY-NC-SA 4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/).

MULTEXT-East would be a great resource for a multilingual, annotated corpus, where there exist not many in NLTK.

We propose the name mte_teip5 as a short string for the corpus inside NLTK.

Regards,
Alex, Tommy and Thomas

**Comment by stevenbird** [comment]
Sorry for the delay. If it's not too late, please submit a PR for your corpus reader when you're ready.

**Comment by jwacalex** [comment]
Are there any requirements for the corpus reader itself?

**Comment by stevenbird** [comment]
Just that it should implement as many of the corpus reader methods as possible/appropriate, cf http://www.nltk.org/howto/corpus.html

**Comment by stieglma** [comment]
The pull request with the corpus reader is done. We could not test if it works with the corpus downloaded via the NLTK download manager as the corpus is not listed there. What was tested is, that the reader works when the corpus is unzipped in the nltk_data/corpora/mte_teip5 directory, as we assumed that this would be the folder the download manager creates.
