### ISSUE TITLE
Tigrigna_Corpus

### ISSUE THREAD

**Issue by JexMan** [nltk/nltk_data#31]
Thank you.

**Comment by stevenbird** [comment]
@gereziher – where is the corpus, and is it freely redistributable?

**Comment by JexMan** [comment]
Thank you.

**Comment by JexMan** [comment]
Thank you.

**Comment by stevenbird** [comment]
Ok, thanks @gereziher

**Comment by JexMan** [comment]
Thank you so much professor!.
