### ISSUE TITLE
README files

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk_data#33]
Normalize corpus README files. Currently some are `README.txt`, but [CorpusReader.readme()](https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/api.py#L130) expects them to be called `README`, cf https://github.com/nltk/nltk/issues/31

**Comment by ewan-klein** [comment]
I think the corpus reader should be modified to accept both. In principle, having an explicit file extension seems like a good thing. 

In fact, I would also like it if we could accept README files in markdown to allow better handling of hyperlinks.

**Comment by sadeghmir** [comment]
(This is a minor but related issue. Let me know if I should have opened a new issue for this.)

The readme file for "treebank" seems to be mislocated. Upon typing treebank.readme() I get this error:
**No such file or directory: '...\nltk_data\corpora\treebank\combined\README'**

The error is rightful, because all readme files are actually located in the _treebank_ root folder not in _combined_.

**Comment by fcbond** [comment]
On Wed, Mar 2, 2016 at 3:42 AM, deKXer notifications@github.com wrote:

> (This is a minor but related issue. Let me know if I should have opened a
> new issue for this.)
> 
> The readme file for "treebank" seems to be mislocated. Upon typing
> treebank.readme() I get this error:
> _No such file or directory:
> '...\nltk_data\corpora\treebank\combined\README'_
> 
> The error is rightful, because all readme files are actually located in
> the _treebank_ root folder not in _combined_.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nltk/nltk_data/issues/33#issuecomment-190869337.
> 
> Perhaps we could either:
> (a) symbolic link the README
> (b) make a new README in combined that is the concatenation of all the
> READMEs

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by sadeghmir** [comment]
There is a separate readme file that contains overall information. It starts with:

> PENN TREEBANK SAMPLE
> http://www.cis.upenn.edu/~treebank/home.html
> 
> This is a ~5% fragment of Penn Treebank, (C) LDC 1995...

It makes sense to use this one as the readme file for the corpus **treebank**. Either a reference to, or the whole content of the other readme files can be added to this file. I noticed that the two other groups (raw and tagged) have their own loaders, which expect their readme files to be in their folders. That should also be taken care of.

Let me know if these changes are acceptable and I can make a move to apply them to **treebank**.

**Comment by fcbond** [comment]
On Wed, Mar 2, 2016 at 10:08 AM, Sadegh notifications@github.com wrote:

> It makes sense to use this one as the readme file for the corpus
> _treebank_. Either a reference to, or the whole content of the other
> readme files can be added to this file. I noticed that the two other groups
> (raw and tagged) have their own loaders, which expect their readme files to
> be in their folders. That should also be taken care of.
> 
> Let me know if these changes are acceptable and I can make a move to apply
> them to _treebank_.

That sounds good.   I think it would be best if each loader gets the
general README+the relevant specialized README.

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by sadeghmir** [comment]
After my fix for _treebank _is merged, I will start standardizing all corpora readme files. Between the two options, README or README.txt, I think the latter is more reasonable. After all, the developers guide to add new corpora [here](https://github.com/nltk/nltk/wiki/Adding-a-Corpus) advises to use README.txt. Let me know what you think and I can get started.

**Comment by fcbond** [comment]
I think README is much more common (4000+ on my system) than README.txt
(129).  It is also what we use in LOGON and the Open Multilingual Wordnet.

So I would  prefer to standardize on README.

On Thu, Mar 3, 2016 at 10:44 AM, Sadegh notifications@github.com wrote:

> After my fix for _treebank _is merged, I will start standardizing all
> corpora readme files. Between the two options, README or README.txt, I
> think the latter is more reasonable. After all, the developers guide to add
> new corpora here https://github.com/nltk/nltk/wiki/Adding-a-Corpus
> advises to use README.txt. Let me know what you think and I can get started.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nltk/nltk_data/issues/33#issuecomment-191551469.

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by sadeghmir** [comment]
Alright. So I edited the developers guide wiki so that it says "include a `README` file (text file with no extension)...". Now I'm just waiting for the pull request #48 to be processed.
