### ISSUE TITLE
Cannot download latest nltk_data

### ISSUE THREAD

**Issue by WheresWardy** [nltk/nltk_data#35]
Not long ago we had a problem downloading nltk data described in the nltk repo under this issue: https://github.com/nltk/nltk/issues/882 where an erroneous extension caused issues downloading nltk data using nltk v2.

It seems the problem has been re-introduced with the following commit: https://github.com/nltk/nltk_data/commit/c9887b508db9728d5acf6787de47af958e459c39 where the `.xml` extension is causing download failures in nltk. Would it be possible to have the same fix applied to remove the erroneous extension?

**Comment by stevenbird** [comment]
Thanks @WheresWardy
