### ISSUE TITLE
Fix typo in name of contributor of Alpino corpus

### ISSUE THREAD

**Issue by SvGeloven** [nltk/nltk_data#39]
Please, fix a typo in the name of contributor of Alpino corpus. In the file https://github.com/nltk/nltk_data/blob/gh-pages/packages/corpora/alpino.xml change the following two lines

```
         contact="Gertjan Van Noord"
         license="Distributed with permission of Gertjan Van Noord"
```

into

```
         contact="Gertjan van Noord"
         license="Distributed with permission of Gertjan van Noord"
```

**Comment by SvGeloven** [comment]
And also in the README in the zip file https://github.com/nltk/nltk_data/blob/gh-pages/packages/corpora/alpino.zip the line

```
Distributed with NLTK with permission of Gertjan Van Noord
```

should be changed to

```
Distributed with NLTK with permission of Gertjan van Noord
```

**Comment by stevenbird** [comment]
Thanks @SvGeloven
