### ISSUE TITLE
Type inconsistency between NLTK Wordnet and OMW for all_lemma_names()

### ISSUE THREAD

**Issue by ghost** [nltk/nltk_data#43]
NLTK's Wordnet and Open Multilingual Wordnet ("OMW") share a common function, but produce output of differing types:

```
import nltk
# Install Open Multilingual Wordnet and Wordnet
# if not already installed.
nltkd = nltk.downloader.Downloader()
for corpus in ['wordnet','omw']:
    if not nltkd.is_installed(corpus):
        nltk.download(corpus)

from nltk.corpus import wordnet as wn
for lang in sorted(wn.langs()):
    print lang, type(wn.all_lemma_names(lang=lang))
```

produces:

```
als <type 'list'>
arb <type 'list'>
bul <type 'list'>
cat <type 'list'>
cmn <type 'list'>
dan <type 'list'>
ell <type 'list'>
eng <type 'dictionary-keyiterator'>
eus <type 'list'>
fas <type 'list'>
fin <type 'list'>
fra <type 'list'>
glg <type 'list'>
heb <type 'list'>
hrv <type 'list'>
ind <type 'list'>
ita <type 'list'>
jpn <type 'list'>
nno <type 'list'>
nob <type 'list'>
pol <type 'list'>
por <type 'list'>
qcn <type 'list'>
slv <type 'list'>
spa <type 'list'>
swe <type 'list'>
tha <type 'list'>
zsm <type 'list'>
```

This inconsistency will cause users to have to use workarounds that result in less comprehensible code than would otherwise be the case. For example, until this bug is fixed, developers may need to use Python's [built-in `list()` function](https://docs.python.org/2/library/functions.html#list) to ensure that a list is returned regardless of which OMW language code is passed to `all_lemma_names()`.

This inconsistency also partly explains the zero result for English (`eng`) in #42 .

**Comment by ekaf** [comment]
Now , the type is an iterator in all cases.
