### ISSUE TITLE
Stopwords for Slovene

### ISSUE THREAD

**Issue by ajdapretnar** [nltk/nltk_data#54]
I have a list of stopwords for Slovene language and I'd like to include it in NLTK, so we can operate with them from within the library. I've tried to submit a PR, but you seem to have all .zip files. What should be in them? .txt? Please give me a bit more elaborate contribution guidelines.

Thanks!

**Comment by stevenbird** [comment]
@ajdapretnar – thanks for your interest. Fine to drop the text file here. A bigger issue is to demonstrate consensus about this particular list. Ideally it comes from a canonical source that is already widely accepted.

**Comment by ajdapretnar** [comment]
@stevenbird Yes, that's the issue here. The Institute that was supposed to provide some of this is not responding to my mails. I've got this list from the wast universe of internet (and it even might be the one they wrote), but I modified it. I removed names of days and months after a debate with my linguist colleagues. If required, I can add them back but the very point of it is one can do additional filtering later. And there were many stopwords missing, so I went through the dictionaries and added them.

As for adding the text file here, I'm not sure that's the proper open-source way of doing it. One should surely open a PR, that is later reviewed, edited (if required) and then merged.

**Comment by ajdapretnar** [comment]
Finally got around to this.
[slovenian-stopwords.txt](https://github.com/nltk/nltk_data/files/2248806/slovenian-stopwords.txt)

The list is included in the [CLARIN database](https://www.clarin.si/repository/xmlui/handle/11356/1109), which I think would be considered pretty standard.

**Comment by ajdapretnar** [comment]
This is a stale issue, but I would really appreciate if the list could be added to the resources. Thanks!

**Comment by zigacernigoj** [comment]
bump

**Comment by stevenbird** [comment]
@ajdapretnar, @zigacernigoj: sorry for the delay

**Comment by zcernigoj** [comment]
No problem. Thanks!

**Comment by zigacernigoj** [comment]
No problem. Thanks!
