### ISSUE TITLE
panlex_lite is out of date

### ISSUE THREAD

**Issue by MartyMacGyver** [nltk/nltk_data#59]
panlex_lite [has been recently updated](https://dev.panlex.org/db/) and is therefore always showing as "out of date" per the nltk downloader (GUI and command line). The current correct data for **index.xml** is as follows:

`<package author="David Kamholz" checksum="255bbe2c06d8e1acfe57cab42052d6cb" id="panlex_lite" license="CC0 1.0 Universal" name="PanLex Lite Corpus" size="2235214249" subdir="corpora" unzip="1" unzipped_size="5917599729" url="http://dev.panlex.org/db/panlex_lite.zip" webpage="http://panlex.org/" />
`

**Comment by MartyMacGyver** [comment]
Cross-platform code used to test the problem and the solution:

    #!/usr/bin/env python3
    
    import os
    import nltk.downloader
    
    cwd = os.getcwd().replace(os.path.sep, '/')
    
    #my_url = 'https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml'
    #my_url = 'file:///{}/nltk-index-old.xml',format(cwd)
    my_url = 'file:///{}/nltk-index-new.xml'.format(cwd)
    
    nltk.downloader.Downloader(server_index_url=my_url).download()

**Comment by stevenbird** [comment]
I have removed Panlex_lite from the NLTK data distribution until we find a better solution. In the meantime, anyone wanting to use it will need to manually download [the latest panlex snapshot](https://db.panlex.org/panlex_lite.zip), unpack it into `$NLTK_DATA/corpora/panlex_lite`, then access the [panlex_lite corpus reader](https://github.com/nltk/nltk/blob/develop/nltk/corpus/__init__.py#L166) using `from nltk.corpus import panlex_lite` in the usual way.
