### ISSUE TITLE
http://nltk.org/nltk_data/ is stale

### ISSUE THREAD

**Issue by kmike** [nltk/nltk_data#6]
For example, size for punkt tokenizer is 5920457 at http://nltk.org/nltk_data/, but it is 6613281 in index.xml. This makes nltk.download think that punkt is always outdated.

**Comment by alvations** [comment]
Sorry for missing this issue out. There shouldn't be any problem with the punkt.zip now in the latest version of nltk and nltk_data. @kmike Are you still having an issue with it?

**Comment by jayvdb** [comment]
I guess this can be closed.
