### ISSUE TITLE
Can't download cmudata

### ISSUE THREAD

**Issue by saralilyb** [nltk/nltk_data#66]
I keep getting a HTTP 503 error trying to download `cmudict` either through the nltk interface or directly from github.

**Comment by gmarmstrong** [comment]
I am unable to replicate this error. What does `nltk.download('cmudict')` output? Do you have the same problem downloading from https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/cmudict.zip directly?

**Comment by saralilyb** [comment]
Seems like it must've been a temporary thing; it works now. Thanks for the followup!
