### ISSUE TITLE
Additional categories for different NLTK usages

### ISSUE THREAD

**Issue by alvations** [nltk/nltk_data#69]
We have `all-corpora` and `all` but it'll be nice if we can several new category that includes:

 - `popular`
   - punkt
   - stopwords
   - wordnet
   - averaged_perceptron_tagger
   - brown
   - movie_reviews
   - words

 - `tokenizers`
   - punkt
   - snowball
   - perluniprops
   - nonbreaking_prefixes

That way I think it's easier to advise users to do the following to install `nltk`:

```
pip install -U nltk
python -m nltk.downloader popular
```

More importantly, I think `all-no-third-party` and `all-third-party`, so that we can separate issues when the third-party datasets/models don't update their checksum to `nltk` when they refresh their data/models. 

@stevenbird Are the suggestions okay? How should we go about adding these categories?

**Comment by stevenbird** [comment]
@alvations: great idea; simply create new collections over in `nltk_data/collections/`
