### ISSUE TITLE
MedBrandList

### ISSUE THREAD

**Issue by abeepathak96** [nltk/nltk_data#77]
[drugs.txt](https://github.com/nltk/nltk_data/files/1048990/drugs.txt)
These are the list of names of brands of the medicines that are currently available in India. 
These are very useful in parsing the clinical free texts.
the plaintext corpus reader will be enough as the corpus reader.
This corpus will be accessible under the Creative Commons ShareAlike license.
@stevenbird

**Comment by stevenbird** [comment]
We don't have capacity to add and maintain custom wordlists like this, sorry. They can be distributed outside of NLTK.
