### ISSUE TITLE
Make gh-pages branch the default

### ISSUE THREAD

**Issue by lamberta** [nltk/nltk_data#8]
You can make the _gh-pages_ branch the GitHub default. Not a big deal, but might help some people browsing around and unfamiliar with the GitHub UI.  Within the _Settings_ tab on the right, there's a dropdown menu for _Default Branch_.

**Comment by kmike** [comment]
+1

**Comment by pquentin** [comment]
+1

**Comment by stevenbird** [comment]
Thanks for this suggestion, and sorry for the huge delay. Done.
