### ISSUE TITLE
HTTP Error 405 when using ntlk.downloader all

### ISSUE THREAD

**Issue by fcw6323** [nltk/nltk_data#84]
python -m nltk.downloader all
/Users/CHUAN/anaconda3/lib/python3.6/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Error loading all: HTTP Error 405: Not allowed.
Error installing package. Retry? [n/y/e]

Any help?

**Comment by alvations** [comment]
Please see nltk/nltk#1787 and https://stackoverflow.com/a/45321530/610569

**Comment by uda** [comment]
Trying to figure out why my tests are failing, I wondered why it uses `https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/` instead of `https://nltk.github.io/nltk_data/`.
I can see why we one would use the githubusercontent for develop branch access, but for production the CDN on github pages should be better IMHO.

**Comment by alvations** [comment]
@uda do you mean https://nltk.github.com/nltk_data/ ? It will be forwarded to http://www.nltk.org/nltk_data/ which will still link to the individual files in https://raw.githubusercontent.com/ =(

But I agree using https://raw.githubusercontent.com/ for anything is inefficient and apparently it's disastrous when users abuses it. 

It'll be good if any engineers have good suggestions on how to approach this. 

Currently, I'm personally vote for putting up resources on http://zenodo.org but setting up it up through the API or one-by-one manually will require some extra free time.

**Comment by uda** [comment]
@alvations you are right, I didn't notice that redirect.

I suggest to use github pages, but you'll just need another subdomain to point at `nltk/nltk_data`'s `gh-pages`, say `data.nltk.org`

**Comment by alvations** [comment]
The same unscalable problem still exist if large no. of users or one high frequecy hits the github server hard enough, if we rely on Github to distribute data/models I think it'll still end up with more 403/405 errors =(

But we should ask Github what exactly is the allowed load on their end. And most probably migrate the data downloads somewhere else too,

**Comment by jayvdb** [comment]
https://github.com/nltk/nltk_data/issues/12 would be a way to resolve this.

**Comment by alvations** [comment]
Pip is nice and Spacy does that too. I'm inclined to do it the spacy way. The downloading and storage part is easy if we follow the spacy style, https://github.com/explosion/spaCy/blob/develop/spacy/cli/download.py 

But that'll also require an overhaul of the downloader.py and data.py in the `nltk` code. 

But I've to read more into the code to understand how they are accessing the models without the user setting the path to the models individually every time.
